plugins {
    id 'java'
}

group = 'su.luochen'
version = '1.0'

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    maven { url 'https://repo.luckperms.me/maven/' }
}

dependencies {
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    compileOnly 'org.spigotmc:spigot-api:26.1.2-R0.1-SNAPSHOT'
    compileOnly 'net.luckperms:api:5.4'

}

test {
    useJUnitPlatform()
}